language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"

before_script:
  - npm install
  - npm install coveralls

script:
  - npm test

after_script: NODE_ENV=test cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js